baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Alexandre Gagnon"
theme = 'mark'

[params]
name = "Minimal Marketing"
license = "MIT"
licenselink = "https://github.com/letItCurl/minimal_marketing/blob/main/LICENSE"
description = "This was just my first dinner - every now and then"


tags = ["blog", "company", "marketing", "landing page"]
features = ["tailwind", "form", "CTA", "Google analytics"]


[original]
  name = "Hugo-Tailwind-3.1"
  author = "4044ever"
  homepage = "https://github.com/4044ever"
  repo = "https://github.com/4044ever/Hugo-Tailwind-3.1"
